name: tp2
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  firebase_auth_web: ^5.13.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  provider: ^6.1.2
  firebase_storage: ^12.3.4
  path: ^1.9.0
  google_fonts: ^6.2.1
  file_picker: ^8.1.3
  tflite: ^1.1.2
  tflite_flutter: ^0.11.0
  image: ^4.3.0
  cloudinary_dart: ^0.0.11
  cloudinary_url_gen: ^1.6.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/model_unquant.tflite
