name: tp2
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0         # Adjusted to the latest version
  firebase_auth: ^5.3.1          # Adjusted to the latest version
  cloud_firestore: ^5.4.4        # Adjusted to the latest version
  intl: ^0.19.0                  # Adjusted to the latest version
  firebase_auth_web: ^5.13.2     # Adjusted to the latest version
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  provider: ^6.1.2
  firebase_storage: ^12.3.4
  path: ^1.9.0
  google_fonts: ^6.2.1
  tflite: ^1.1.2
  #tflite: ^1.0.4                 # If you added this

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true